### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by gopher-confocal** [ND-HowardGroup/Instant-Image-Denoising#4]
I get the following error message when I launch the Noise2Noise plugin:
``[INFO] No TF library found in C:\Users\MARY_B~1\Desktop\Fiji.app\lib\.
[INFO] Version of TensorFlow: TF 1.15.0 CPU
[INFO] Input image type is 16-bit uint.
[ERROR] Command errored: Noise2Noise Denoising
java.lang.IncompatibleClassChangeError: Found interface org.tensorflow.OperationBuilder, but class was expected
	at net.image.denoising.demo.Noise2Noise_Denoising.normalizeImage(Noise2Noise_Denoising.java:233)
	at net.image.denoising.demo.Noise2Noise_Denoising.process_image(Noise2Noise_Denoising.java:253)
	at net.image.denoising.demo.Noise2Noise_Denoising.run(Noise2Noise_Denoising.java:135)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`

Plus I get this error message too:
``(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 320MB of 48789MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw error
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw error
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw error
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:131)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.tensorflow.OperationBuilder, but class was expected
	at net.image.denoising.demo.Noise2Noise_Denoising.normalizeImage(Noise2Noise_Denoising.java:233)
	at net.image.denoising.demo.Noise2Noise_Denoising.process_image(Noise2Noise_Denoising.java:253)
	at net.image.denoising.demo.Noise2Noise_Denoising.run(Noise2Noise_Denoising.java:135)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	... 6 more
I have no coding experience, so I don't know how to interpret or remedy the error messages. What has gone wrong and how to fix it? Thank you for your help.
Mary

**Comment by varunmannam** [comment]
Thanks for checking our plugin. 
However, the TF version of TF 1.15.0 CPU is not supported at the time, we built this Noise2Noise FIJI application. 
Can you please change the TF version to 1.12.0 and try again our method? 

Instructions: https://github.com/ND-HowardGroup/Instant-Image-Denoising/blob/master/Plugins/Instructions_to_Install_Image_denoising_plugins.docx 
See section: 
<img width="224" alt="image" src="https://github.com/ND-HowardGroup/Instant-Image-Denoising/assets/38203187/71b560ca-7cd7-48ec-8269-f565e99970ad">
