### ISSUE TITLE
Plugin suddenly not running

### ISSUE THREAD

**Issue by gopher-confocal** [ND-HowardGroup/Instant-Image-Denoising#5]
I started getting an error message when I attempt to run the Noise2Noise plugin:

``[Fri May 31 15:11:28 CDT 2024] [INFO] [] Version of TensorFlow: TF 1.12.0 CPU
[Fri May 31 15:11:28 CDT 2024] [INFO] [] Input image type is 16-bit uint.
[Fri May 31 15:11:28 CDT 2024] [ERROR] [] Command errored: Noise2Noise Denoising
java.lang.IncompatibleClassChangeError: Found interface org.tensorflow.OperationBuilder, but class was expected
	at net.image.denoising.demo.Noise2Noise_Denoising.normalizeImage(Noise2Noise_Denoising.java:233)
	at net.image.denoising.demo.Noise2Noise_Denoising.process_image(Noise2Noise_Denoising.java:253)
	at net.image.denoising.demo.Noise2Noise_Denoising.run(Noise2Noise_Denoising.java:135)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

I don't know what this error message means. Is there some sort of incompatibility? What needs to be done? Thank you for your help.

**Comment by varunmannam** [comment]
Hi, thanks for trying our Noise2Noise algorithm. I do believe the installation of the tensorflow plugin might be an issue. can you follow these simple instructions about the plugin installation? https://github.com/ND-HowardGroup/Instant-Image-Denoising/blob/master/Plugins/Instructions_to_Install_Image_denoising_plugins.docx

**Comment by gopher-confocal** [comment]
I followed the simple instructions exactly and I still get the same error
message.
________________________________________________
Mary E. Brown, Pharm.D.
Imaging Specialist/Researcher 3
University Imaging Centers
Jackson Hall, rm. 1-151
321 Church St. SE
Minneapolis, MN 55455
Email: ***@***.***
Phone: 773-458-3090

**Comment by gopher-confocal** [comment]
Please do not close the issue when it is not resolved. The plugin had run smoothly for quite a few months then suddenly stops working. The fact that it ran well for months proves that I installed the plugin correctly! What do the error messages mean? Thank you.

**Comment by gopher-confocal** [comment]
Thank you for reopening this. I'm not sure how to interpret the error messages. One of the lines says, "java.lang.IncompatibleClassChangeError: Found interface org.tensorflow.OperationBuilder, but class was expected". Does this mean there is some incompatibility with another plugin? Was FIJI expecting a class file instead of a java file? I have no coding experience, so I am merely guessing here. Thank you.

**Comment by gopher-confocal** [comment]
Hi Varun,

Thank you for re-opening this issue. I always install with the simple
instructions. I put the Step 1 files into the Plugins folder and the Step 2
folders into a model folder, then I start FIJI. The plugin worked
marvelously for about a year until late last week and I'm not sure what I
did differently. These are the error messages I get when executing the
plugin:
FIJI Console:
[INFO] Version of TensorFlow: TF 1.12.0 GPU (CUDA 9.0, CuDNN >= 7.2)
[INFO] Input image type is 16-bit uint.
[ERROR] Command errored: Noise2Noise Denoising
java.lang.UnsatisfiedLinkError:
org.tensorflow.OperationBuilder.allocate(JLjava/lang/String;Ljava/lang/String;)J
at org.tensorflow.OperationBuilder.allocate(Native Method)
at org.tensorflow.OperationBuilder.<init>(OperationBuilder.java:44)
at org.tensorflow.Graph.opBuilder(Graph.java:101)
at
net.image.denoising.demo.Noise2Noise_Denoising.normalizeImage(Noise2Noise_Denoising.java:233)
at
net.image.denoising.demo.Noise2Noise_Denoising.process_image(Noise2Noise_Denoising.java:253)
at
net.image.denoising.demo.Noise2Noise_Denoising.run(Noise2Noise_Denoising.java:135)
at org.scijava.command.CommandModule.run(CommandModule.java:196)
at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
at
org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

FIJI Log:
[Tue Jun 04 10:52:46 CDT 2024] [INFO] [] Version of TensorFlow: TF 1.12.0
GPU (CUDA 9.0, CuDNN >= 7.2)
[Tue Jun 04 10:52:46 CDT 2024] [INFO] [] Input image type is 16-bit uint.
[Tue Jun 04 10:52:46 CDT 2024] [ERROR] [] Command errored: Noise2Noise
Denoising
java.lang.UnsatisfiedLinkError:
org.tensorflow.OperationBuilder.allocate(JLjava/lang/String;Ljava/lang/String;)J
at org.tensorflow.OperationBuilder.allocate(Native Method)
at org.tensorflow.OperationBuilder.<init>(OperationBuilder.java:44)
at org.tensorflow.Graph.opBuilder(Graph.java:101)
at
net.image.denoising.demo.Noise2Noise_Denoising.normalizeImage(Noise2Noise_Denoising.java:233)
at
net.image.denoising.demo.Noise2Noise_Denoising.process_image(Noise2Noise_Denoising.java:253)
at
net.image.denoising.demo.Noise2Noise_Denoising.run(Noise2Noise_Denoising.java:135)
at org.scijava.command.CommandModule.run(CommandModule.java:196)
at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
at
org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

Exception window:
(Fiji Is Just) ImageJ 2.14.0/1.54i; Java 1.8.0_322 [64-bit]; Windows 10
10.0; 323MB of 56000MB (<1%)

java.lang.RuntimeException: java.util.concurrent.ExecutionException:
java.lang.RuntimeException: Module threw error
at
net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
at
net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
at ij.IJ.runPlugIn(IJ.java)
at ij.Executer.runCommand(Executer.java:152)
at ij.Executer.run(Executer.java:70)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException:
java.lang.RuntimeException: Module threw error
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at
net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
... 5 more
Caused by: java.lang.RuntimeException: Module threw error
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:131)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
at
org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
... 1 more
Caused by: java.lang.UnsatisfiedLinkError:
org.tensorflow.OperationBuilder.allocate(JLjava/lang/String;Ljava/lang/String;)J
at org.tensorflow.OperationBuilder.allocate(Native Method)
at org.tensorflow.OperationBuilder.<init>(OperationBuilder.java:44)
at org.tensorflow.Graph.opBuilder(Graph.java:101)
at
net.image.denoising.demo.Noise2Noise_Denoising.normalizeImage(Noise2Noise_Denoising.java:233)
at
net.image.denoising.demo.Noise2Noise_Denoising.process_image(Noise2Noise_Denoising.java:253)
at
net.image.denoising.demo.Noise2Noise_Denoising.run(Noise2Noise_Denoising.java:135)
at org.scijava.command.CommandModule.run(CommandModule.java:196)
at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
... 6 more


Is there some sort of incompatibility? How do you interpret these error
messages? We want to publish a FIJI macro I wrote which incorporates this
denoising plugin, so having it fail now when I'm supposed to write a
methods section is the worst possible timing. I desperately need to get
this plugin working again! I do get the same error messages with a fresh
installation of FIJI. Thank you for your help.
________________________________________________
Mary E. Brown, Pharm.D.
Imaging Specialist/Researcher 3
University Imaging Centers
Jackson Hall, rm. 1-151
321 Church St. SE
Minneapolis, MN 55455
Email: ***@***.***
Phone: 773-458-3090

**Comment by gopher-confocal** [comment]
By the process of adding and removing plugins one at a time, I have determined that the Noise2Noise plugin has an incompatibility with the latest update of the CSBDeep plugin. Is this something you intend to investigate and repair? Thanks.
